### ISSUE TITLE
Testar sonar frontal

### ISSUE THREAD

**Issue by lennedy** [IFRN-SC/robo_hardware#12]
Testar sonar frontal e identificar se o sonar está lendo valores corretamente e identificando se existe um obstáculo a sua frente.

**Comment by zaqmarlon** [comment]
Informações... @lennedy

**Comment by lennedy** [comment]
Que tipo de informações, @isaacmarlon ?
Essa tarefa é para testar os sensor sonar utilizando o código versão uno.
